# Generated by Django 5.2.8 on 2025-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='original_name',
            field=models.CharField(default='application/octet-stream', max_length=255),
            preserve_default=False,
        ),
    ]
