# Generated by Django 6.0 on 2025-12-18 13:48

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_encryptedfile_delete_encrypted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to=files.models.encrypted_upload_path),
        ),
    ]
